title: Movie List
email: pylypchuk.tolik@gmail.com
description: Movie List
baseurl: MovieList
url: ""
github_username:  TolikPylypchuk

remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-feed
  - jekyll-seo-tag

heading_anchors: true

aux_links:
  "View on GitHub":
    - "https://github.com/TolikPylypchuk/MovieList"

aux_links_new_tab: true

back_to_top: true
back_to_top_text: "Back to top"
